### PR TITLE
add support for complete url

### PR DESCRIPTION
**Pull request by thosil**
In KeycloakURL you can now specify a "real" url like `https://example.com:8443/auth`

- if there's no scheme, https:// is added
- only http and https are authorized (I don't see any other scheme that could be used)

There's still a special case (not yet handled) where you're hosting a keycloak server behind the same reverse proxy than your app and you just want to specify "/auth" in KeycloakURL.

I add some unit tests and tried to test it locally, the traefik doc is wrong about how to load local plugins.
"Local Mode" [here](https://plugins.traefik.io/install) use experimental.plugins instead of experimental.localplugins.
But it's correct in the [example plugin](https://github.com/traefik/plugindemo#local-mode)

 I had to do this in my docker-compose.yml:
```yaml
version: "3.9"

services:
  proxy:
    image: traefik:v2.10
    hostname: "proxy-webserver"
    command:
      - --global.checknewversion=false
      - --log=true
      - --log.level=DEBUG
      - --ping
      - --accesslog=true
      - --api.debug=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-test
      - --providers.docker.swarmmode=true
      - --providers.file.directory=/etc/traefik
      - --entrypoints.https.address=:10443      
      - --entrypoints.traefik.address=:18081
      - --metrics.prometheus=true
      - --experimental.localplugins.keycloakopenid.modulename=github.com/Gwojda/keycloakopenid
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "10443:10443"
      - "18081:18081"
    networks:
      - traefik-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik:/etc/traefik:ro
      - path/to/keycloakopenid:/plugins-local/src/github.com/Gwojda/keycloakopenid
```
see --experimental.localplugins.... and mounting the directory of the plugin in the right place.

It's my first experience in go, feel free to correct my mistakes.

### CODE REVIEW

**Comment by thosil** [comment]
@Gwojda not sure you saw this PR or had the time to check it?

**Comment by Gwojda** [comment]
didnt had time yet
Have you tested it?

**Comment by thosil** [comment]
yes, in my lab, but you should double check :-)

**Comment by Skiepp** [comment]
PR included in PR #13

**Pull request merged**
